%% epoching, epoch rejection, response times and ERP calculation
clear all
close all

%% PATHS, names and variables
% EEG
mac_switch = 1; % 1: work, 2: home

if ispc
   PATH = 'D:\DATA\grailswitch\';
elseif ismac
    if mac_switch == 1
        PATH = '/Volumes/Work2TB/Seafile/grailswitch';
    elseif mac_switch == 2
        PATH = '/Users/julianreiser/Seafile/grailswitch';
    end % mac_switch
end

PATH_RAW = [PATH '/data/RAW/'];
PATH_ICA = [PATH '/data/processed/ICA'];
PATH_EEG = [PATH '/data/processed/EEG'];
PATH_PRUNED =[PATH '/data/processed/PRUNED'];

% LISTS / STATS
PATH_LIST = [PATH '/lists'];
PATH_COND = [PATH_LIST '/conditions'];
PATH_STAT = [PATH '/stats_rework'];
PATH_PLOT = [PATH '/plots'];
subjlist = {'02','03','04','05','06','07','09','10','11','12','13','15','16','18','19','20','21','22','23','24','25','27'};

%% Load GND_grailswitch
GND = load([PATH_STAT '/FMUT/GND_grailswitch_cue_audi.mat']);
GND_cue_audi = GND.GND;

GND = load([PATH_STAT '/FMUT/GND_grailswitch_cue_visu.mat']);
GND_cue_visu = GND.GND;

GND = load([PATH_STAT '/FMUT/GND_grailswitch_tar_audi.mat']);
GND_tar_audi = GND.GND;

GND = load([PATH_STAT '/FMUT/GND_grailswitch_tar_visu.mat']);
GND_tar_visu = GND.GND;

% correct wrong times-scaling
if GND_cue_audi.time_pts(end) < 1000
    GND_cue_audi.time_pts = GND_cue_audi.time_pts * 1000;
    GND_cue_visu.time_pts = GND_cue_visu.time_pts * 1000;
    GND_tar_audi.time_pts = GND_tar_audi.time_pts * 1000;
    GND_tar_visu.time_pts = GND_tar_visu.time_pts * 1000;
end

%% set GND parameters
%Define some variables
nPerm = 1e4;
chanHood = 75;

% P1 params
P1StimWindow = [80 160];
P1Chans = {'POz','PO3','PO4','PO7','PO8','PO9','PO10','Oz','O1','O2'};

% CNV params
CNVStimWindow = [-150 50];
CNVChans = {'F1','F2','Fz','FC1','FC2','Cz','C1','C2'};

% N2 params
N2StimWindow = [250 400];
N2Chans = {'F1','F2','Fz','FC1','FC2','Cz','C1','C2'};

% P3 params
P3StimWindow = [300 600];
P3Chans = {'CPz','CP1','CP2','Pz','P1','P2','P3','P4','POz','PO3','PO4'};

%% Full factorial designs
%% Stim-related CNV
GND_cue_SCNV_audi = FclustGND(GND_cue_audi, ...
                    'bins', 1:9, ...
                    'factor_names', {'mixed', 'move'}, ...
                    'factor_levels', [3, 3], ...
                    'time_wind', CNVStimWindow, ...
                    'include_chans',CNVChans, ...
                    'chan_hood', chanHood, ...
                    'n_perm', nPerm, ...
                    'plot_raster','yes', ...
                    'save_GND', 'no');

save([PATH_STAT '/FMUT/GND_GS_StimCNV_fullFactorial_cue_audi.mat'],'GND_cue_SCNV_audi');

GND_cue_SCNV_visu = FclustGND(GND_cue_visu, ...
                    'bins', 1:9, ...
                    'factor_names', {'mixed', 'move'}, ...
                    'factor_levels', [3, 3], ...
                    'time_wind', CNVStimWindow, ...
                    'include_chans',CNVChans, ...
                    'chan_hood', chanHood, ...
                    'n_perm', nPerm, ...
                    'plot_raster','yes', ...
                    'save_GND', 'no');

save([PATH_STAT '/FMUT/GND_GS_StimCNV_fullFactorial_cue_visu.mat'],'GND_cue_SCNV_visu');

close all

%% Stim-related P3
GND_tar_SP3_audi = FclustGND(GND_tar_audi, ...
                'bins', 1:9, ...
                'factor_names', {'mixed', 'move'}, ...
                'factor_levels', [3, 3], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
save([PATH_STAT '/FMUT/GND_GS_StimP3_fullFactorial_tar_audi.mat'],'GND_tar_SP3_audi');

GND_tar_SP3_visu = FclustGND(GND_tar_visu, ...
                'bins', 1:9, ...
                'factor_names', {'mixed', 'move'}, ...
                'factor_levels', [3, 3], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
save([PATH_STAT '/FMUT/GND_GS_StimP3_fullFactorial_tar_visu.mat'],'GND_tar_SP3_visu');

close all;

%% Extract necessary reports and means for plotting
%% CNV audi means
report_results(GND_cue_SCNV_audi,1)
%CNV_mixed_audi_Means = get_mean_amplitude(GND_cue_SCNV_audi,1,'effect','mixed')
CNV_move_audi_Means = get_mean_amplitude(GND_cue_SCNV_audi,1,'effect','move')

% CNV visu means
report_results(GND_cue_SCNV_audi,1)
CNV_mixed_visu_Means = get_mean_amplitude(GND_cue_SCNV_visu,1,'effect','mixed')
CNV_move_visu_Means = get_mean_amplitude(GND_cue_SCNV_visu,1,'effect','move')

%% P3 means
report_results(GND_tar_SP3_audi,1);
P3_mixed_audi_Means = get_mean_amplitude(GND_tar_SP3_audi,1,'effect','mixed')
P3_move_audi_Means = get_mean_amplitude(GND_tar_SP3_audi,1,'effect','move')
%P3_mixedXmove_audi_Means = get_mean_amplitude(GND_tar_SP3_audi,1,'effect','mixedXmove')

report_results(GND_tar_SP3_visu,1);
P3_mixed_visu_Means = get_mean_amplitude(GND_tar_SP3_visu,1,'effect','mixed')
P3_move_visu_Means = get_mean_amplitude(GND_tar_SP3_visu,1,'effect','move')
P3_mixedXmove_visu_Means = get_mean_amplitude(GND_tar_SP3_visu,1,'effect','mixedXmove')

%% CNV
% CNV mixed
% CNV_mixed_audi_plotmeans = [mean(CNV_mixed_audi_Means.data(:,1:3:end),[1,2]),mean(CNV_mixed_audi_Means.data(:,2:3:end),[1,2]),mean(CNV_mixed_audi_Means.data(:,3:3:end),[1,2])];
% CNV_mixed_audi_plotsems = [std(CNV_mixed_audi_Means.data(:,1:3:end),0,[1,2]) / sqrt(size(CNV_mixed_audi_Means.data,1)),std(CNV_mixed_audi_Means.data(:,2:3:end),0,[1,2]) / sqrt(size(CNV_mixed_audi_Means.data,1)),std(CNV_mixed_audi_Means.data(:,3:3:end),0,[1,2]) / sqrt(size(CNV_mixed_audi_Means.data,1))];
% CNV_mixed_audi_plotstds = [std(CNV_mixed_audi_Means.data(:,1:3:end),0,[1,2]),std(CNV_mixed_audi_Means.data(:,2:3:end),0,[1,2]),std(CNV_mixed_audi_Means.data(:,3:3:end),0,[1,2])];
% figure;
% set(gcf, 'Units', 'centimeters', 'Position', [0, 0, 20, 20], 'PaperUnits', 'centimeters', 'PaperSize', [21,21])
% lb_niceBARplot([CNV_mixed_audi_plotmeans(1);CNV_mixed_audi_plotmeans(2);CNV_mixed_audi_plotmeans(3)], ...
%                [CNV_mixed_audi_plotsems(1);CNV_mixed_audi_plotsems(2);CNV_mixed_audi_plotsems(3)], ...
%                'Auditory CNV amplitude - difficulty','µV',{'single','repeat','switch'},[-2,0])
% saveas(gcf,[PATH_PLOT '/FMUT/effects/CNV_means_mixed_audi.png']); close gcf;

% CNV move
CNV_move_audi_plotmeans = [mean(CNV_move_audi_Means.data(:,1:3),[1,2]),mean(CNV_move_audi_Means.data(:,4:6),[1,2]),mean(CNV_move_audi_Means.data(:,7:9),[1,2])];
CNV_move_audi_plotsems = [std(CNV_move_audi_Means.data(:,1:3),0,[1,2]) / sqrt(size(CNV_move_audi_Means.data,1)),std(CNV_move_audi_Means.data(:,4:6),0,[1,2]) / sqrt(size(CNV_move_audi_Means.data,1)),std(CNV_move_audi_Means.data(:,7:9),0,[1,2]) / sqrt(size(CNV_move_audi_Means.data,1))];
CNV_move_audi_plotstds = [std(CNV_move_audi_Means.data(:,1:3),0,[1,2]),std(CNV_move_audi_Means.data(:,4:6),0,[1,2]),std(CNV_move_audi_Means.data(:,7:9),0,[1,2])];
figure;
set(gcf, 'Units', 'centimeters', 'Position', [0, 0, 20, 20], 'PaperUnits', 'centimeters', 'PaperSize', [21,21])
lb_niceBARplot([CNV_move_audi_plotmeans(1);CNV_move_audi_plotmeans(2);CNV_move_audi_plotmeans(3)], ...
               [CNV_move_audi_plotsems(1);CNV_move_audi_plotsems(2);CNV_move_audi_plotsems(3)], ...
               'Auditory CNV amplitude - move','µV',{'stand','walk','perturbation'},[-2,0])
saveas(gcf,[PATH_PLOT '/FMUT/effects/CNV_means_move_audi.png']); close gcf;

% CNV mixed
CNV_mixed_visu_plotmeans = [mean(CNV_mixed_visu_Means.data(:,1:3:end),[1,2]),mean(CNV_mixed_visu_Means.data(:,2:3:end),[1,2]),mean(CNV_mixed_visu_Means.data(:,3:3:end),[1,2])];
CNV_mixed_visu_plotsems = [std(CNV_mixed_visu_Means.data(:,1:3:end),0,[1,2]) / sqrt(size(CNV_mixed_visu_Means.data,1)),std(CNV_mixed_visu_Means.data(:,2:3:end),0,[1,2]) / sqrt(size(CNV_mixed_visu_Means.data,1)),std(CNV_mixed_visu_Means.data(:,3:3:end),0,[1,2]) / sqrt(size(CNV_mixed_visu_Means.data,1))];
CNV_mixed_visu_plotstds = [std(CNV_mixed_visu_Means.data(:,1:3:end),0,[1,2]),std(CNV_mixed_visu_Means.data(:,2:3:end),0,[1,2]),std(CNV_mixed_visu_Means.data(:,3:3:end),0,[1,2])];
figure;
set(gcf, 'Units', 'centimeters', 'Position', [0, 0, 20, 20], 'PaperUnits', 'centimeters', 'PaperSize', [21,21])
lb_niceBARplot([CNV_mixed_visu_plotmeans(1);CNV_mixed_visu_plotmeans(2);CNV_mixed_visu_plotmeans(3)], ...
               [CNV_mixed_visu_plotsems(1);CNV_mixed_visu_plotsems(2);CNV_mixed_visu_plotsems(3)], ...
               'Visual CNV amplitude - difficulty','µV',{'single','repeat','switch'},[-2,0])
saveas(gcf,[PATH_PLOT '/FMUT/effects/CNV_means_mixed_visu.png']); close gcf;

% CNV move
CNV_move_visu_plotmeans = [mean(CNV_move_visu_Means.data(:,1:3),[1,2]),mean(CNV_move_visu_Means.data(:,4:6),[1,2]),mean(CNV_move_visu_Means.data(:,7:9),[1,2])];
CNV_move_visu_plotsems = [std(CNV_move_visu_Means.data(:,1:3),0,[1,2]) / sqrt(size(CNV_move_visu_Means.data,1)),std(CNV_move_visu_Means.data(:,4:6),0,[1,2]) / sqrt(size(CNV_move_visu_Means.data,1)),std(CNV_move_visu_Means.data(:,7:9),0,[1,2]) / sqrt(size(CNV_move_visu_Means.data,1))];
CNV_move_visu_plotstds = [std(CNV_move_visu_Means.data(:,1:3),0,[1,2]),std(CNV_move_visu_Means.data(:,4:6),0,[1,2]),std(CNV_move_visu_Means.data(:,7:9),0,[1,2])];
figure;
set(gcf, 'Units', 'centimeters', 'Position', [0, 0, 20, 20], 'PaperUnits', 'centimeters', 'PaperSize', [21,21])
lb_niceBARplot([CNV_move_visu_plotmeans(1);CNV_move_visu_plotmeans(2);CNV_move_visu_plotmeans(3)], ...
               [CNV_move_visu_plotsems(1);CNV_move_visu_plotsems(2);CNV_move_visu_plotsems(3)], ...
               'Visual CNV amplitude - move','µV',{'stand','walk','perturbation'},[-2,0])
saveas(gcf,[PATH_PLOT '/FMUT/effects/CNV_means_move_visu.png']); close gcf;

%% P3
% P3 mixed
P3_mixed_audi_plotmeans = [mean(P3_mixed_audi_Means.data(:,1:3:end),[1,2]),mean(P3_mixed_audi_Means.data(:,2:3:end),[1,2]),mean(P3_mixed_audi_Means.data(:,3:3:end),[1,2])];
P3_mixed_audi_plotsems = [std(P3_mixed_audi_Means.data(:,1:3:end),0,[1,2]) / sqrt(size(P3_mixed_audi_Means.data,1)),std(P3_mixed_audi_Means.data(:,2:3:end),0,[1,2]) / sqrt(size(P3_mixed_audi_Means.data,1)),std(P3_mixed_audi_Means.data(:,3:3:end),0,[1,2]) / sqrt(size(P3_mixed_audi_Means.data,1))];
P3_mixed_audi_plotstds = [std(P3_mixed_audi_Means.data(:,1:3:end),0,[1,2]),std(P3_mixed_audi_Means.data(:,2:3:end),0,[1,2]),std(P3_mixed_audi_Means.data(:,3:3:end),0,[1,2])];
figure;
set(gcf, 'Units', 'centimeters', 'Position', [0, 0, 20, 20], 'PaperUnits', 'centimeters', 'PaperSize', [21,21])
lb_niceBARplot([P3_mixed_audi_plotmeans(1);P3_mixed_audi_plotmeans(2);P3_mixed_audi_plotmeans(3)], ...
               [P3_mixed_audi_plotsems(1);P3_mixed_audi_plotsems(2);P3_mixed_audi_plotsems(3)], ...
               'Auditory P3 amplitude - difficulty','µV',{'single','repeat','switch'},[0,5])
saveas(gcf,[PATH_PLOT '/FMUT/effects/P3_means_mixed_audi.png']); close gcf;

% P3 move
P3_move_audi_plotmeans = [mean(P3_move_audi_Means.data(:,1:3),[1,2]),mean(P3_move_audi_Means.data(:,4:6),[1,2]),mean(P3_move_audi_Means.data(:,7:9),[1,2])];
P3_move_audi_plotsems = [std(P3_move_audi_Means.data(:,1:3),0,[1,2]) / sqrt(size(P3_move_audi_Means.data,1)),std(P3_move_audi_Means.data(:,4:6),0,[1,2]) / sqrt(size(P3_move_audi_Means.data,1)),std(P3_move_audi_Means.data(:,7:9),0,[1,2]) / sqrt(size(P3_move_audi_Means.data,1))];
P3_move_audi_plotstds = [std(P3_move_audi_Means.data(:,1:3),0,[1,2]),std(P3_move_audi_Means.data(:,4:6),0,[1,2]),std(P3_move_audi_Means.data(:,7:9),0,[1,2])];
figure;
set(gcf, 'Units', 'centimeters', 'Position', [0, 0, 20, 20], 'PaperUnits', 'centimeters', 'PaperSize', [21,21])
lb_niceBARplot([P3_move_audi_plotmeans(1);P3_move_audi_plotmeans(2);P3_move_audi_plotmeans(3)], ...
               [P3_move_audi_plotsems(1);P3_move_audi_plotsems(2);P3_move_audi_plotsems(3)], ...
               'Auditory P3 amplitude - move','µV',{'stand','walk','perturbation'},[0,5])
saveas(gcf,[PATH_PLOT '/FMUT/effects/P3_means_move_audi.png']); close gcf;

% P3 mixed
P3_mixed_visu_plotmeans = [mean(P3_mixed_visu_Means.data(:,1:3:end),[1,2]),mean(P3_mixed_visu_Means.data(:,2:3:end),[1,2]),mean(P3_mixed_visu_Means.data(:,3:3:end),[1,2])];
P3_mixed_visu_plotsems = [std(P3_mixed_visu_Means.data(:,1:3:end),0,[1,2]) / sqrt(size(P3_mixed_visu_Means.data,1)),std(P3_mixed_visu_Means.data(:,2:3:end),0,[1,2]) / sqrt(size(P3_mixed_visu_Means.data,1)),std(P3_mixed_visu_Means.data(:,3:3:end),0,[1,2]) / sqrt(size(P3_mixed_visu_Means.data,1))];
P3_mixed_visu_plotstds = [std(P3_mixed_visu_Means.data(:,1:3:end),0,[1,2]),std(P3_mixed_visu_Means.data(:,2:3:end),0,[1,2]),std(P3_mixed_visu_Means.data(:,3:3:end),0,[1,2])];
figure;
set(gcf, 'Units', 'centimeters', 'Position', [0, 0, 20, 20], 'PaperUnits', 'centimeters', 'PaperSize', [21,21])
lb_niceBARplot([P3_mixed_visu_plotmeans(1);P3_mixed_visu_plotmeans(2);P3_mixed_visu_plotmeans(3)], ...
               [P3_mixed_visu_plotsems(1);P3_mixed_visu_plotsems(2);P3_mixed_visu_plotsems(3)], ...
               'Visual P3 amplitude - difficulty','µV',{'single','repeat','switch'},[0,5])
saveas(gcf,[PATH_PLOT '/FMUT/effects/P3_means_mixed_visu.png']); close gcf;

% P3 move
P3_move_visu_plotmeans = [mean(P3_move_visu_Means.data(:,1:3),[1,2]),mean(P3_move_visu_Means.data(:,4:6),[1,2]),mean(P3_move_visu_Means.data(:,7:9),[1,2])];
P3_move_visu_plotsems = [std(P3_move_visu_Means.data(:,1:3),0,[1,2]) / sqrt(size(P3_move_visu_Means.data,1)),std(P3_move_visu_Means.data(:,4:6),0,[1,2]) / sqrt(size(P3_move_visu_Means.data,1)),std(P3_move_visu_Means.data(:,7:9),0,[1,2]) / sqrt(size(P3_move_visu_Means.data,1))];
P3_move_visu_plotstds = [std(P3_move_visu_Means.data(:,1:3),0,[1,2]),std(P3_move_visu_Means.data(:,4:6),0,[1,2]),std(P3_move_visu_Means.data(:,7:9),0,[1,2])];
figure;
set(gcf, 'Units', 'centimeters', 'Position', [0, 0, 20, 20], 'PaperUnits', 'centimeters', 'PaperSize', [21,21])
lb_niceBARplot([P3_move_visu_plotmeans(1);P3_move_visu_plotmeans(2);P3_move_visu_plotmeans(3)], ...
               [P3_move_visu_plotsems(1);P3_move_visu_plotsems(2);P3_move_visu_plotsems(3)], ...
               'Visual P3 amplitude - move','µV',{'stand','walk','perturbation'},[0,5])
saveas(gcf,[PATH_PLOT '/FMUT/effects/P3_means_move_visu.png']); close gcf;

% P3 mixed X move
% P3_mixedXmove_audi_plotmeans = [mean(P3_mixedXmove_audi_Means.data(:,[1]),[1,2]),mean(P3_mixedXmove_audi_Means.data(:,[2]),[1,2]),mean(P3_mixedXmove_audi_Means.data(:,[3]),[1,2]),...
%                            mean(P3_mixedXmove_audi_Means.data(:,[4]),[1,2]),mean(P3_mixedXmove_audi_Means.data(:,[5]),[1,2]),mean(P3_mixedXmove_audi_Means.data(:,[6]),[1,2]),...
%                            mean(P3_mixedXmove_audi_Means.data(:,[7]),[1,2]),mean(P3_mixedXmove_audi_Means.data(:,[8]),[1,2]),mean(P3_mixedXmove_audi_Means.data(:,[9]),[1,2])];
% P3_mixedXmove_audi_plotsems = [std(P3_mixedXmove_audi_Means.data(:,[1]),0,[1,2]) / sqrt(size(P3_mixedXmove_audi_Means.data,1)),std(P3_mixedXmove_audi_Means.data(:,[2]),0,[1,2]) / sqrt(size(P3_mixedXmove_audi_Means.data,1)),std(P3_mixedXmove_audi_Means.data(:,[3]),0,[1,2]) / sqrt(size(P3_mixedXmove_audi_Means.data,1)),...
%                           std(P3_mixedXmove_audi_Means.data(:,[4]),0,[1,2]) / sqrt(size(P3_mixedXmove_audi_Means.data,1)),std(P3_mixedXmove_audi_Means.data(:,[5]),0,[1,2]) / sqrt(size(P3_mixedXmove_audi_Means.data,1)),std(P3_mixedXmove_audi_Means.data(:,[6]),0,[1,2]) / sqrt(size(P3_mixedXmove_audi_Means.data,1)),...
%                           std(P3_mixedXmove_audi_Means.data(:,[7]),0,[1,2]) / sqrt(size(P3_mixedXmove_audi_Means.data,1)),std(P3_mixedXmove_audi_Means.data(:,[8]),0,[1,2]) / sqrt(size(P3_mixedXmove_audi_Means.data,1)),std(P3_mixedXmove_audi_Means.data(:,[9]),0,[1,2]) / sqrt(size(P3_mixedXmove_audi_Means.data,1))];
% P3_mixedXmove_audi_plotstds = [std(P3_mixedXmove_audi_Means.data(:,[1]),0,[1,2]),std(P3_mixedXmove_audi_Means.data(:,[2]),0,[1,2]),std(P3_mixedXmove_audi_Means.data(:,[3]),0,[1,2]),...
%                           std(P3_mixedXmove_audi_Means.data(:,[4]),0,[1,2]),std(P3_mixedXmove_audi_Means.data(:,[5]),0,[1,2]),std(P3_mixedXmove_audi_Means.data(:,[6]),0,[1,2]),...
%                           std(P3_mixedXmove_audi_Means.data(:,[7]),0,[1,2]),std(P3_mixedXmove_audi_Means.data(:,[8]),0,[1,2]),std(P3_mixedXmove_audi_Means.data(:,[9]),0,[1,2])];
% figure;
% set(gcf, 'Units', 'centimeters', 'Position', [0, 0, 20, 20], 'PaperUnits', 'centimeters', 'PaperSize', [21,21])
% 
% lb_niceInteractionPlot([P3_mixedXmove_audi_plotmeans(1),P3_mixedXmove_audi_plotmeans(2),P3_mixedXmove_audi_plotmeans(3);P3_mixedXmove_audi_plotmeans(4),P3_mixedXmove_audi_plotmeans(5),P3_mixedXmove_audi_plotmeans(6);P3_mixedXmove_audi_plotmeans(7),P3_mixedXmove_audi_plotmeans(8),P3_mixedXmove_audi_plotmeans(9)]', ...
%                        [P3_mixedXmove_audi_plotsems(1),P3_mixedXmove_audi_plotsems(2),P3_mixedXmove_audi_plotsems(3);P3_mixedXmove_audi_plotsems(4),P3_mixedXmove_audi_plotsems(5),P3_mixedXmove_audi_plotsems(6);P3_mixedXmove_audi_plotsems(7),P3_mixedXmove_audi_plotsems(8),P3_mixedXmove_audi_plotsems(9)]', ...
%                        'Auditory P3 amplitude - difficulty x move','µV',{'single','repeat','switch'},[0,5],'label_legend',{'stand','walk','perturbation'},'locs_legend','best')
% saveas(gcf,[PATH_PLOT '/FMUT/effects/P3means_mixedXmove_audi.png']); close gcf;

% P3 mixed X move
P3_mixedXmove_visu_plotmeans = [mean(P3_mixedXmove_visu_Means.data(:,[1]),[1,2]),mean(P3_mixedXmove_visu_Means.data(:,[2]),[1,2]),mean(P3_mixedXmove_visu_Means.data(:,[3]),[1,2]),...
                           mean(P3_mixedXmove_visu_Means.data(:,[4]),[1,2]),mean(P3_mixedXmove_visu_Means.data(:,[5]),[1,2]),mean(P3_mixedXmove_visu_Means.data(:,[6]),[1,2]),...
                           mean(P3_mixedXmove_visu_Means.data(:,[7]),[1,2]),mean(P3_mixedXmove_visu_Means.data(:,[8]),[1,2]),mean(P3_mixedXmove_visu_Means.data(:,[9]),[1,2])];
P3_mixedXmove_visu_plotsems = [std(P3_mixedXmove_visu_Means.data(:,[1]),0,[1,2]) / sqrt(size(P3_mixedXmove_visu_Means.data,1)),std(P3_mixedXmove_visu_Means.data(:,[2]),0,[1,2]) / sqrt(size(P3_mixedXmove_visu_Means.data,1)),std(P3_mixedXmove_visu_Means.data(:,[3]),0,[1,2]) / sqrt(size(P3_mixedXmove_visu_Means.data,1)),...
                          std(P3_mixedXmove_visu_Means.data(:,[4]),0,[1,2]) / sqrt(size(P3_mixedXmove_visu_Means.data,1)),std(P3_mixedXmove_visu_Means.data(:,[5]),0,[1,2]) / sqrt(size(P3_mixedXmove_visu_Means.data,1)),std(P3_mixedXmove_visu_Means.data(:,[6]),0,[1,2]) / sqrt(size(P3_mixedXmove_visu_Means.data,1)),...
                          std(P3_mixedXmove_visu_Means.data(:,[7]),0,[1,2]) / sqrt(size(P3_mixedXmove_visu_Means.data,1)),std(P3_mixedXmove_visu_Means.data(:,[8]),0,[1,2]) / sqrt(size(P3_mixedXmove_visu_Means.data,1)),std(P3_mixedXmove_visu_Means.data(:,[9]),0,[1,2]) / sqrt(size(P3_mixedXmove_visu_Means.data,1))];
P3_mixedXmove_visu_plotstds = [std(P3_mixedXmove_visu_Means.data(:,[1]),0,[1,2]),std(P3_mixedXmove_visu_Means.data(:,[2]),0,[1,2]),std(P3_mixedXmove_visu_Means.data(:,[3]),0,[1,2]),...
                          std(P3_mixedXmove_visu_Means.data(:,[4]),0,[1,2]),std(P3_mixedXmove_visu_Means.data(:,[5]),0,[1,2]),std(P3_mixedXmove_visu_Means.data(:,[6]),0,[1,2]),...
                          std(P3_mixedXmove_visu_Means.data(:,[7]),0,[1,2]),std(P3_mixedXmove_visu_Means.data(:,[8]),0,[1,2]),std(P3_mixedXmove_visu_Means.data(:,[9]),0,[1,2])];

figure;
set(gcf, 'Units', 'centimeters', 'Position', [0, 0, 20, 20], 'PaperUnits', 'centimeters', 'PaperSize', [21,21])

 close all

%% CNV post-hoc tests audi
% CNV: mixed
% Add bins for following up main effects of modality
GND_cue_SCNV_audi = gs_bin_mean(GND_cue_SCNV_audi, 1:3:length(GND_cue_SCNV_audi.condesc), 'single task',1,'single task'); %bin 10
GND_cue_SCNV_audi = gs_bin_mean(GND_cue_SCNV_audi, 2:3:length(GND_cue_SCNV_audi.condesc), 'repeat trials', 1, 'repeat trials'); %bin 11
GND_cue_SCNV_audi = gs_bin_mean(GND_cue_SCNV_audi, 3:3:length(GND_cue_SCNV_audi.condesc), 'switch trials', 1, 'switch trials'); %bin 12

% CNV: single vs. mixed
GND_cue_SCNV_audi = FclustGND(GND_cue_SCNV_audi, ...
                'bins', [10,11], ...
                'factor_names', {'mixed'}, ...
                'factor_levels', [2], ...
                'time_wind', CNVStimWindow, ...
                'include_chans',CNVChans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
gcf; title('N1 - mixed')
saveas(gcf,[PATH_PLOT '/FMUT/raster/CNV_audi_ph_single_repeat.png']); close gcf;

% CNV: single vs. mixed
GND_cue_SCNV_audi = FclustGND(GND_cue_SCNV_audi, ...
                'bins', [10,12], ...
                'factor_names', {'mixed'}, ...
                'factor_levels', [2], ...
                'time_wind', CNVStimWindow, ...
                'include_chans',CNVChans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
gcf; title('N1 - mixed')
saveas(gcf,[PATH_PLOT '/FMUT/raster/CNV_audi_ph_single_switch.png']); close gcf;

GND_cue_SCNV_audi = FclustGND(GND_cue_SCNV_audi, ...
                'bins', [11,12], ...
                'factor_names', {'mixed'}, ...
                'factor_levels', [2], ...
                'time_wind', CNVStimWindow, ...
                'include_chans',CNVChans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
gcf; title('N1 - mixed')
saveas(gcf,[PATH_PLOT '/FMUT/raster/CNV_audi_ph_repeat_switch.png']); close gcf;

% Add bins for following up main effects of move
GND_cue_SCNV_audi = gs_bin_mean(GND_cue_SCNV_audi, [1:3], 'stand',1,'stand'); %bin 13
GND_cue_SCNV_audi = gs_bin_mean(GND_cue_SCNV_audi, [4:6], 'walk', 1, 'walk'); %bin 14
GND_cue_SCNV_audi = gs_bin_mean(GND_cue_SCNV_audi, [7:9], 'perturbation', 1, 'perturbation'); %bin 15

% CNV: stand vs. walk
GND_cue_SCNV_audi = FclustGND(GND_cue_SCNV_audi, ...
                'bins', [13,14], ...
                'factor_names', {'move'}, ...
                'factor_levels', [2], ...
                'time_wind', CNVStimWindow, ...
                'include_chans',CNVChans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/CNV_audi_ph_stand_walk.png']); close gcf;

% CNV: stand vs. pert
GND_cue_SCNV_audi = FclustGND(GND_cue_SCNV_audi, ...
                'bins', [13,15], ...
                'factor_names', {'move'}, ...
                'factor_levels', [2], ...
                'time_wind', CNVStimWindow, ...
                'include_chans',CNVChans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/CNV_audi_ph_stand_pert.png']); close gcf;

% CNV: walk vs. pert
GND_cue_SCNV_audi = FclustGND(GND_cue_SCNV_audi, ...
                'bins', [14,15], ...
                'factor_names', {'move'}, ...
                'factor_levels', [2], ...
                'time_wind', CNVStimWindow, ...
                'include_chans',CNVChans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/CNV_audi_ph_walk_pert.png']); close gcf;

%% CNV post-hoc tests visu
% CNV: mixed
% Add bins for following up main effects of modality
GND_cue_SCNV_visu = gs_bin_mean(GND_cue_SCNV_visu, 1:3:length(GND_cue_SCNV_visu.condesc), 'single task',1,'single task'); %bin 10
GND_cue_SCNV_visu = gs_bin_mean(GND_cue_SCNV_visu, 2:3:length(GND_cue_SCNV_visu.condesc), 'repeat trials', 1, 'repeat trials'); %bin 11
GND_cue_SCNV_visu = gs_bin_mean(GND_cue_SCNV_visu, 3:3:length(GND_cue_SCNV_visu.condesc), 'switch trials', 1, 'switch trials'); %bin 12

% CNV: single vs. mixed
GND_cue_SCNV_visu = FclustGND(GND_cue_SCNV_visu, ...
                'bins', [10,11], ...
                'factor_names', {'mixed'}, ...
                'factor_levels', [2], ...
                'time_wind', CNVStimWindow, ...
                'include_chans',CNVChans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
gcf; title('N1 - mixed')
saveas(gcf,[PATH_PLOT '/FMUT/raster/CNV_visu_ph_single_repeat.png']); close gcf;

% CNV: single vs. mixed
GND_cue_SCNV_visu = FclustGND(GND_cue_SCNV_visu, ...
                'bins', [10,12], ...
                'factor_names', {'mixed'}, ...
                'factor_levels', [2], ...
                'time_wind', CNVStimWindow, ...
                'include_chans',CNVChans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
gcf; title('N1 - mixed')
saveas(gcf,[PATH_PLOT '/FMUT/raster/CNV_visu_ph_single_switch.png']); close gcf;

GND_cue_SCNV_visu = FclustGND(GND_cue_SCNV_visu, ...
                'bins', [11,12], ...
                'factor_names', {'mixed'}, ...
                'factor_levels', [2], ...
                'time_wind', CNVStimWindow, ...
                'include_chans',CNVChans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
gcf; title('N1 - mixed')
saveas(gcf,[PATH_PLOT '/FMUT/raster/CNV_visu_ph_repeat_switch.png']); close gcf;

% Add bins for following up main effects of move
GND_cue_SCNV_visu = gs_bin_mean(GND_cue_SCNV_visu, [1:3], 'stand',1,'stand'); %bin 13
GND_cue_SCNV_visu = gs_bin_mean(GND_cue_SCNV_visu, [4:6], 'walk', 1, 'walk'); %bin 14
GND_cue_SCNV_visu = gs_bin_mean(GND_cue_SCNV_visu, [7:9], 'perturbation', 1, 'perturbation'); %bin 15

% CNV: stand vs. walk
GND_cue_SCNV_visu = FclustGND(GND_cue_SCNV_visu, ...
                'bins', [13,14], ...
                'factor_names', {'move'}, ...
                'factor_levels', [2], ...
                'time_wind', CNVStimWindow, ...
                'include_chans',CNVChans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/CNV_visu_ph_stand_walk.png']); close gcf;

% CNV: stand vs. pert
GND_cue_SCNV_visu = FclustGND(GND_cue_SCNV_visu, ...
                'bins', [13,15], ...
                'factor_names', {'move'}, ...
                'factor_levels', [2], ...
                'time_wind', CNVStimWindow, ...
                'include_chans',CNVChans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/CNV_visu_ph_stand_pert.png']); close gcf;

% CNV: walk vs. pert
GND_cue_SCNV_visu = FclustGND(GND_cue_SCNV_visu, ...
                'bins', [14,15], ...
                'factor_names', {'move'}, ...
                'factor_levels', [2], ...
                'time_wind', CNVStimWindow, ...
                'include_chans',CNVChans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/CNV_visu_ph_walk_pert.png']); close gcf;

%% P3 post-hoc tests audi
% P3: mixed
% Add bins for following up main effects of modality
GND_tar_SP3_audi = gs_bin_mean(GND_tar_SP3_audi, 1:3:length(GND_tar_SP3_audi.condesc), 'single task',1,'single task'); %bin 10
GND_tar_SP3_audi = gs_bin_mean(GND_tar_SP3_audi, 2:3:length(GND_tar_SP3_audi.condesc), 'repeat trials', 1, 'repeat trials'); %bin 11
GND_tar_SP3_audi = gs_bin_mean(GND_tar_SP3_audi, 3:3:length(GND_tar_SP3_audi.condesc), 'switch trials', 1, 'switch trials'); %bin 12

% P3: single vs. repeat
GND_tar_SP3_audi = FclustGND(GND_tar_SP3_audi, ...
                'bins', [10,11], ...
                'factor_names', {'mixed'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
gcf; title('N1 - mixed')
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_audi_pvh_single_repeat.png']); close gcf;

% P3: single vs. switch
GND_tar_SP3_audi = FclustGND(GND_tar_SP3_audi, ...
                'bins', [10,12], ...
                'factor_names', {'mixed'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
gcf; title('N1 - mixed')
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_audi_ph_single_switch.png']); close gcf;

GND_tar_SP3_audi = FclustGND(GND_tar_SP3_audi, ...
                'bins', [11,12], ...
                'factor_names', {'mixed'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
gcf; title('N1 - mixed')
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_audi_ph_repeat_switch.png']); close gcf;

% Add bins for following up main effects of move
GND_tar_SP3_audi = gs_bin_mean(GND_tar_SP3_audi, [1:3], 'stand',1,'stand'); %bin 13
GND_tar_SP3_audi = gs_bin_mean(GND_tar_SP3_audi, [4:6], 'walk', 1, 'walk'); %bin 14
GND_tar_SP3_audi = gs_bin_mean(GND_tar_SP3_audi, [7:9], 'perturbation', 1, 'perturbation'); %bin 15

% P3: stand vs. walk
GND_tar_SP3_audi = FclustGND(GND_tar_SP3_audi, ...
                'bins', [13,14], ...
                'factor_names', {'move'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_audi_ph_stand_walk.png']); close gcf;

% P3: stand vs. pert
GND_tar_SP3_audi = FclustGND(GND_tar_SP3_audi, ...
                'bins', [13,15], ...
                'factor_names', {'move'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_audi_ph_stand_pert.png']); close gcf;

% P3: walk vs. pert
GND_tar_SP3_audi = FclustGND(GND_tar_SP3_audi, ...
                'bins', [14,15], ...
                'factor_names', {'move'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_audi_ph_walk_pert.png']); close gcf;

% P3: mixed x move interaction
% Add bins for following up interaction effects of moda x move
GND_tar_SP3_audi = gs_bin_mean(GND_tar_SP3_audi, [1], 'single stand',1,'single stand'); %bin 16
GND_tar_SP3_audi = gs_bin_mean(GND_tar_SP3_audi, [4], 'single walk',1,'single walk'); %bin 17
GND_tar_SP3_audi = gs_bin_mean(GND_tar_SP3_audi, [7], 'single perturbation',1,'single perturbation'); %bin 18

GND_tar_SP3_audi = gs_bin_mean(GND_tar_SP3_audi, [2], 'repeat stand',1,'repeat stand'); %bin 19
GND_tar_SP3_audi = gs_bin_mean(GND_tar_SP3_audi, [5], 'repeat walk',1,'repeat walk'); %bin 20
GND_tar_SP3_audi = gs_bin_mean(GND_tar_SP3_audi, [8], 'repeat perturbation',1,'repeat perturbation'); %bin 21

GND_tar_SP3_audi = gs_bin_mean(GND_tar_SP3_audi, [3], 'switch stand',1,'switch stand'); %bin 22
GND_tar_SP3_audi = gs_bin_mean(GND_tar_SP3_audi, [6], 'switch walk',1,'switch walk'); %bin 23
GND_tar_SP3_audi = gs_bin_mean(GND_tar_SP3_audi, [9], 'switch perturbation',1,'switch perturbation'); %bin 24

% P3: stand single vs. stand repeat
GND_tar_SP3_audi = FclustGND(GND_tar_SP3_audi, ...
                'bins', [16,19], ...
                'factor_names', {'mixed'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_audi_ph_stand_single_repeat.png']); close gcf;

% P3: stand single vs. stand switch
GND_tar_SP3_audi = FclustGND(GND_tar_SP3_audi, ...
                'bins', [16,22], ...
                'factor_names', {'mixed'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_audi_ph_stand_single_switch.png']); close gcf;

% P3: stand repeat vs. stand switch
GND_tar_SP3_audi = FclustGND(GND_tar_SP3_audi, ...
                'bins', [19,22], ...
                'factor_names', {'mixed'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_audi_ph_stand_repeat_switch.png']); close gcf;

% P3: walk single vs. walk repeat
GND_tar_SP3_audi = FclustGND(GND_tar_SP3_audi, ...
                'bins', [17,20], ...
                'factor_names', {'mixed'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_audi_ph_walk_single_repeat.png']); close gcf;

% P3: walk single vs. walk switch
GND_tar_SP3_audi = FclustGND(GND_tar_SP3_audi, ...
                'bins', [17,23], ...
                'factor_names', {'mixed'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_audi_ph_walk_single_switch.png']); close gcf;

% P3: walk repeat vs. walk switch
GND_tar_SP3_audi = FclustGND(GND_tar_SP3_audi, ...
                'bins', [20,23], ...
                'factor_names', {'mixed'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_audi_ph_walk_repeat_switch.png']); close gcf;

% P3: pert single vs. pert repeat
GND_tar_SP3_audi = FclustGND(GND_tar_SP3_audi, ...
                'bins', [18,21], ...
                'factor_names', {'mixed'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_audi_ph_pert_single_repeat.png']); close gcf;

% P3: pert single vs. pert switch
GND_tar_SP3_audi = FclustGND(GND_tar_SP3_audi, ...
                'bins', [18,24], ...
                'factor_names', {'mixed'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_audi_ph_pert_single_switch.png']); close gcf;
 
% P3: pert repeat vs. pert switch
GND_tar_SP3_audi = FclustGND(GND_tar_SP3_audi, ...
                'bins', [21,24], ...
                'factor_names', {'mixed'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_audi_ph_pert_repeat_switch.png']); close gcf;
close all

%% other way around
% P3: single stand vs. walk
GND_tar_SP3_audi = FclustGND(GND_tar_SP3_audi, ...
                'bins', [16,17], ...
                'factor_names', {'move'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_audi_ph_single_stand_walk.png']); close gcf;

% P3: single stand vs. pert
GND_tar_SP3_audi = FclustGND(GND_tar_SP3_audi, ...
                'bins', [16,18], ...
                'factor_names', {'move'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_audi_ph_single_stand_pert.png']); close gcf;

% P3: single walk vs pert
GND_tar_SP3_audi = FclustGND(GND_tar_SP3_audi, ...
                'bins', [17,18], ...
                'factor_names', {'move'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_audi_ph_single_walk_pert.png']); close gcf;

% P3: repeat stand vs. walk
GND_tar_SP3_audi = FclustGND(GND_tar_SP3_audi, ...
                'bins', [19,20], ...
                'factor_names', {'move'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_audi_ph_repeat_stand_walk.png']); close gcf;

% P3: repeat stand vs. pert
GND_tar_SP3_audi = FclustGND(GND_tar_SP3_audi, ...
                'bins', [19,21], ...
                'factor_names', {'move'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_audi_phrepeat_stand_pert.png']); close gcf;

% P3: repeat walk vs. pert
GND_tar_SP3_audi = FclustGND(GND_tar_SP3_audi, ...
                'bins', [20,21], ...
                'factor_names', {'move'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_audi_ph_repeat_walk_pert.png']); close gcf;

% P3: switch stand vs. walk
GND_tar_SP3_audi = FclustGND(GND_tar_SP3_audi, ...
                'bins', [22,23], ...
                'factor_names', {'move'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_audi_ph_switch_stand_walk.png']); close gcf;
 
% P3: switch stand vs. pert
GND_tar_SP3_audi = FclustGND(GND_tar_SP3_audi, ...
                'bins', [22,24], ...
                'factor_names', {'move'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_audi_ph_switch_stand_pert.png']); close gcf;
close all

% P3: switch walk vs. pert
GND_tar_SP3_audi = FclustGND(GND_tar_SP3_audi, ...
                'bins', [23,24], ...
                'factor_names', {'move'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_audi_ph_switch_walk_pert.png']); close gcf;

%% P3 post-hoc tests visu
% P3: mixed
% Add bins for following up main effects of modality
GND_tar_SP3_visu = gs_bin_mean(GND_tar_SP3_visu, 1:3:length(GND_tar_SP3_visu.condesc), 'single task',1,'single task'); %bin 10
GND_tar_SP3_visu = gs_bin_mean(GND_tar_SP3_visu, 2:3:length(GND_tar_SP3_visu.condesc), 'repeat trials', 1, 'repeat trials'); %bin 11
GND_tar_SP3_visu = gs_bin_mean(GND_tar_SP3_visu, 3:3:length(GND_tar_SP3_visu.condesc), 'switch trials', 1, 'switch trials'); %bin 12

% P3: single vs. mixed
GND_tar_SP3_visu = FclustGND(GND_tar_SP3_visu, ...
                'bins', [10,11], ...
                'factor_names', {'mixed'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
gcf; title('N1 - mixed')
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_visu_ph_single_repeat.png']); close gcf;

% P3: single vs. mixed
GND_tar_SP3_visu = FclustGND(GND_tar_SP3_visu, ...
                'bins', [10,12], ...
                'factor_names', {'mixed'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
gcf; title('N1 - mixed')
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_visu_ph_single_switch.png']); close gcf;

GND_tar_SP3_visu = FclustGND(GND_tar_SP3_visu, ...
                'bins', [11,12], ...
                'factor_names', {'mixed'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
gcf; title('N1 - mixed')
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_visu_ph_repeat_switch.png']); close gcf;

% Add bins for following up main effects of move
GND_tar_SP3_visu = gs_bin_mean(GND_tar_SP3_visu, [1:3], 'stand',1,'stand'); %bin 13
GND_tar_SP3_visu = gs_bin_mean(GND_tar_SP3_visu, [4:6], 'walk', 1, 'walk'); %bin 14
GND_tar_SP3_visu = gs_bin_mean(GND_tar_SP3_visu, [7:9], 'perturbation', 1, 'perturbation'); %bin 15

% P3: stand vs. walk
GND_tar_SP3_visu = FclustGND(GND_tar_SP3_visu, ...
                'bins', [13,14], ...
                'factor_names', {'move'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_visu_ph_stand_walk.png']); close gcf;

% P3: stand vs. pert
GND_tar_SP3_visu = FclustGND(GND_tar_SP3_visu, ...
                'bins', [13,15], ...
                'factor_names', {'move'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_visu_ph_stand_pert.png']); close gcf;

% P3: walk vs. pert
GND_tar_SP3_visu = FclustGND(GND_tar_SP3_visu, ...
                'bins', [14,15], ...
                'factor_names', {'move'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_visu_ph_walk_pert.png']); close gcf;

% P3: mixed x move interaction
% Add bins for following up interaction effects of moda x move
GND_tar_SP3_visu = gs_bin_mean(GND_tar_SP3_visu, [1], 'single stand',1,'single stand'); %bin 16
GND_tar_SP3_visu = gs_bin_mean(GND_tar_SP3_visu, [4], 'single walk',1,'single walk'); %bin 17
GND_tar_SP3_visu = gs_bin_mean(GND_tar_SP3_visu, [7], 'single perturbation',1,'single perturbation'); %bin 18

GND_tar_SP3_visu = gs_bin_mean(GND_tar_SP3_visu, [2], 'repeat stand',1,'repeat stand'); %bin 19
GND_tar_SP3_visu = gs_bin_mean(GND_tar_SP3_visu, [5], 'repeat walk',1,'repeat walk'); %bin 20
GND_tar_SP3_visu = gs_bin_mean(GND_tar_SP3_visu, [8], 'repeat perturbation',1,'repeat perturbation'); %bin 21

GND_tar_SP3_visu = gs_bin_mean(GND_tar_SP3_visu, [3], 'switch stand',1,'switch stand'); %bin 22
GND_tar_SP3_visu = gs_bin_mean(GND_tar_SP3_visu, [6], 'switch walk',1,'switch walk'); %bin 23
GND_tar_SP3_visu = gs_bin_mean(GND_tar_SP3_visu, [9], 'switch perturbation',1,'switch perturbation'); %bin 24

% P3: stand single vs. stand repeat
GND_tar_SP3_visu = FclustGND(GND_tar_SP3_visu, ...
                'bins', [16,19], ...
                'factor_names', {'mixed'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_visu_ph_stand_single_repeat.png']); close gcf;

% P3: stand single vs. stand switch
GND_tar_SP3_visu = FclustGND(GND_tar_SP3_visu, ...
                'bins', [16,22], ...
                'factor_names', {'mixed'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_visu_ph_stand_single_switch.png']); close gcf;

% P3: stand repeat vs. stand switch
GND_tar_SP3_visu = FclustGND(GND_tar_SP3_visu, ...
                'bins', [19,22], ...
                'factor_names', {'mixed'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_visu_ph_stand_repeat_switch.png']); close gcf;

% P3: walk single vs. walk repeat
GND_tar_SP3_visu = FclustGND(GND_tar_SP3_visu, ...
                'bins', [17,20], ...
                'factor_names', {'mixed'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_visu_ph_walk_single_repeat.png']); close gcf;

% P3: walk single vs. walk switch
GND_tar_SP3_visu = FclustGND(GND_tar_SP3_visu, ...
                'bins', [17,23], ...
                'factor_names', {'mixed'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_visu_ph_walk_single_switch.png']); close gcf;

% P3: walk repeat vs. walk switch
GND_tar_SP3_visu = FclustGND(GND_tar_SP3_visu, ...
                'bins', [20,23], ...
                'factor_names', {'mixed'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_visu_ph_walk_repeat_switch.png']); close gcf;

% P3: pert single vs. pert repeat
GND_tar_SP3_visu = FclustGND(GND_tar_SP3_visu, ...
                'bins', [18,21], ...
                'factor_names', {'mixed'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_visu_ph_pert_single_repeat.png']); close gcf;

% P3: pert single vs. pert switch
GND_tar_SP3_visu = FclustGND(GND_tar_SP3_visu, ...
                'bins', [18,24], ...
                'factor_names', {'mixed'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_visu_ph_pert_single_switch.png']); close gcf;
 
% P3: pert repeat vs. pert switch
GND_tar_SP3_visu = FclustGND(GND_tar_SP3_visu, ...
                'bins', [21,24], ...
                'factor_names', {'mixed'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_visu_ph_pert_repeat_switch.png']); close gcf;
close all

%% other way around
% P3: single stand vs. walk
GND_tar_SP3_visu = FclustGND(GND_tar_SP3_visu, ...
                'bins', [16,17], ...
                'factor_names', {'move'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_visu_ph_single_stand_walk.png']); close gcf;

% P3: single stand vs. pert
GND_tar_SP3_visu = FclustGND(GND_tar_SP3_visu, ...
                'bins', [16,18], ...
                'factor_names', {'move'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_visu_ph_single_stand_pert.png']); close gcf;

% P3: single walk vs pert
GND_tar_SP3_visu = FclustGND(GND_tar_SP3_visu, ...
                'bins', [17,18], ...
                'factor_names', {'move'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_visu_ph_single_walk_pert.png']); close gcf;

% P3: repeat stand vs. walk
GND_tar_SP3_visu = FclustGND(GND_tar_SP3_visu, ...
                'bins', [19,20], ...
                'factor_names', {'move'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_visu_ph_repeat_stand_walk.png']); close gcf;

% P3: repeat stand vs. pert
GND_tar_SP3_visu = FclustGND(GND_tar_SP3_visu, ...
                'bins', [19,21], ...
                'factor_names', {'move'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_visu_ph_repeat_stand_pert.png']); close gcf;

% P3: repeat walk vs. pert
GND_tar_SP3_visu = FclustGND(GND_tar_SP3_visu, ...
                'bins', [20,21], ...
                'factor_names', {'move'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_visu_ph_repeat_walk_pert.png']); close gcf;

% P3: switch stand vs. walk
GND_tar_SP3_visu = FclustGND(GND_tar_SP3_visu, ...
                'bins', [22,23], ...
                'factor_names', {'move'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_visu_ph_switch_stand_walk.png']); close gcf;
 
% P3: switch stand vs. pert
GND_tar_SP3_visu = FclustGND(GND_tar_SP3_visu, ...
                'bins', [22,24], ...
                'factor_names', {'move'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_visu_ph_switch_stand_pert.png']); close gcf;
close all

% P3: switch walk vs. pert
GND_tar_SP3_visu = FclustGND(GND_tar_SP3_visu, ...
                'bins', [23,24], ...
                'factor_names', {'move'}, ...
                'factor_levels', [2], ...
                'time_wind', P3StimWindow, ...
                'include_chans',P3Chans, ...
                'chan_hood', chanHood, ...
                'n_perm', nPerm, ...
                'plot_raster','yes', ...
                'save_GND', 'no');
saveas(gcf,[PATH_PLOT '/FMUT/raster/P3_visu_ph_switch_walk_pert.png']); close gcf;